### ISSUE TITLE
I'm really appreciate your work. thanks you.

### ISSUE THREAD

**Issue by studyingeugene** [ali-zafari/TBTC#1]
I have a little question.
when drawing RD-curve like in your "README.MD", how do you plot different (bpp, PSNR) pairs?

there are 4 points of SwinT-ChARM on your graph.
Did you train 4 model with different lambda scale?
or is there an option to control rate in a trained model?

If you trained  4 model with different lambda scale, can I know your lamda scales? and If it's possible, can I get pretrained parameters?

Thanks for reading, and your great work.

**Comment by ali-zafari** [comment]
Thanks for your interest in this repository. It seems your question is resolved. 

However to make it clear for potential future reference, the rate-distortion curve shows performance of 16 separately trained models. The four lambda values for each architecture is: 0.0018, 0.0067, 0.025, 0.0932

**Comment by studyingeugene** [comment]
Thanks for your reply and kindness.

**Comment by studyingeugene** [comment]
You said that lambdas are: {0.0018, 0.0067, 0.025, 0.0932}.
but, I think What you really mean is {0.0018, 0.0067, 0.025, 0.0093}.
beacause  the value 0.0932 is so high for plotting with other three values.
Is it your meaning?
